// <auto-generated />
using System;
using FurnitureStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureStore.Migrations
{
    [DbContext(typeof(furnitureStoreContext))]
    [Migration("20251128234038_manyimagesss")]
    partial class manyimagesss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurnitureStore.Models.Cart", b =>
                {
                    b.Property<int>("Cart_id")
                        .HasColumnType("int");

                    b.Property<int>("Items_ID")
                        .HasColumnType("int");

                    b.HasKey("Cart_id");

                    b.HasIndex("Items_ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FurnitureStore.Models.Item", b =>
                {
                    b.Property<int>("Items_ID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Items_ID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FurnitureStore.Models.PurchasedItem", b =>
                {
                    b.Property<int>("PurchasedItems_ID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DatePurchased")
                        .HasColumnType("date");

                    b.Property<int>("Items_ID")
                        .HasColumnType("int");

                    b.HasKey("PurchasedItems_ID");

                    b.HasIndex("Items_ID");

                    b.ToTable("PurchasedItems");
                });

            modelBuilder.Entity("FurnitureStore.Models.WishList", b =>
                {
                    b.Property<int>("WishList_ID")
                        .HasColumnType("int");

                    b.Property<int>("Items_ID")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("WishList_ID");

                    b.HasIndex("Items_ID");

                    b.ToTable("WishList", (string)null);
                });

            modelBuilder.Entity("FurnitureStore.Models.tblImage", b =>
                {
                    b.Property<int>("Images_ID")
                        .HasColumnType("int");

                    b.Property<byte[]>("image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("items_ID")
                        .HasColumnType("int");

                    b.HasKey("Images_ID");

                    b.HasIndex("items_ID");

                    b.ToTable("tblImage");
                });

            modelBuilder.Entity("FurnitureStore.Models.Cart", b =>
                {
                    b.HasOne("FurnitureStore.Models.Item", "Items")
                        .WithMany("Carts")
                        .HasForeignKey("Items_ID")
                        .IsRequired()
                        .HasConstraintName("FK_Carts_Items");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FurnitureStore.Models.PurchasedItem", b =>
                {
                    b.HasOne("FurnitureStore.Models.Item", "Items")
                        .WithMany("PurchasedItems")
                        .HasForeignKey("Items_ID")
                        .IsRequired()
                        .HasConstraintName("FK_PurchasedItems_Items");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FurnitureStore.Models.WishList", b =>
                {
                    b.HasOne("FurnitureStore.Models.Item", "Items")
                        .WithMany("WishLists")
                        .HasForeignKey("Items_ID")
                        .IsRequired()
                        .HasConstraintName("FK_WishList_Items");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FurnitureStore.Models.tblImage", b =>
                {
                    b.HasOne("FurnitureStore.Models.Item", "items")
                        .WithMany("Images")
                        .HasForeignKey("items_ID")
                        .IsRequired()
                        .HasConstraintName("FK_tblImages_Items");

                    b.Navigation("items");
                });

            modelBuilder.Entity("FurnitureStore.Models.Item", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Images");

                    b.Navigation("PurchasedItems");

                    b.Navigation("WishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
