// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FurnitureStore.Models;

public partial class furnitureStoreContext : DbContext
{
    public furnitureStoreContext(DbContextOptions<furnitureStoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<PurchasedItem> PurchasedItems { get; set; }

    public virtual DbSet<WishList> WishLists { get; set; }
    public virtual DbSet<tblImage> tblImage { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Cart_id);

            entity.Property(e => e.Cart_id).ValueGeneratedNever();

            entity.HasOne(d => d.Items).WithMany(p => p.Carts)
                .HasForeignKey(d => d.Items_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Carts_Items");
        });
        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.Items_ID);
            entity.Property(e => e.Items_ID).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            // REMOVED: The old imagesNavigation relationship configuration
        });

        modelBuilder.Entity<PurchasedItem>(entity =>
        {
            entity.HasKey(e => e.PurchasedItems_ID);

            entity.Property(e => e.PurchasedItems_ID).ValueGeneratedNever();

            entity.HasOne(d => d.Items).WithMany(p => p.PurchasedItems)
                .HasForeignKey(d => d.Items_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PurchasedItems_Items");
        });

        modelBuilder.Entity<WishList>(entity =>
        {
            entity.HasKey(e => e.WishList_ID);

            entity.ToTable("WishList");

            entity.Property(e => e.WishList_ID).ValueGeneratedNever();
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Items).WithMany(p => p.WishLists)
                .HasForeignKey(d => d.Items_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WishList_Items");
        });

        modelBuilder.Entity<tblImage>(entity =>
        {
            entity.HasKey(e => e.Images_ID);
            entity.Property(e => e.Images_ID).ValueGeneratedNever();
            entity.Property(e => e.image).IsRequired();

            // UPDATED: Configure the one-to-many relationship
            entity.HasOne(d => d.items)                   // Each image has one Item
                  .WithMany(p => p.Images)               // Each Item has many Images
                  .HasForeignKey(d => d.items_ID)          // Foreign key in tblImage
                  .OnDelete(DeleteBehavior.ClientSetNull)
                  .HasConstraintName("FK_tblImages_Items");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}