// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FurnitureStore.Models;

public partial class Item
{
    [Key]
    public int Items_ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal UnitPrice { get; set; }

    public virtual ICollection<tblImage> Images { get; set; } = new List<tblImage>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<PurchasedItem> PurchasedItems { get; set; } = new List<PurchasedItem>();

    public virtual ICollection<WishList> WishLists { get; set; } = new List<WishList>();
}