// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FurnitureStore.Models;

public partial class PurchasedItem
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PurchasedItems_ID { get; set; }

    public DateOnly DatePurchased { get; set; }

    public int Items_ID { get; set; }

    public virtual Item Items { get; set; }

}